title:              성철이의 개발공부
email:              kimsc1218@gmail.com
description:        개발을 진행하며 습득한 내용을 정리하는 블로그
author:             김성철
baseurl:            "/"
url:                "https://kkimsungchul.github.io"


# Social Profiles
twitter_username:   
github_username:    kkimsungchul
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
asset_url: /assets
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
